name: macOS VNC - WEB ACCESS
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Tools
        run: |
          brew install cloudflared
          # On installe un petit pont qui transforme le VNC en page Web
          brew install novnc

      - name: Enable VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all -allowAccessFor -allUsers
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw P@ssw0rd123!

      - name: Start Web Bridge & Tunnel
        run: |
          # On lance websockify pour transformer le port 5900 (VNC) en port 6080 (Web)
          # Utilise le chemin complet pour novnc/websockify
          $(brew --prefix novnc)/bin/novnc_proxy --vnc localhost:5900 --listen 6080 &
          sleep 5
          
          echo "🚀 Ouverture du tunnel Web..."
          cloudflared tunnel --url http://localhost:6080
