name: macOS VNC - NGROK
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Ngrok & Force Display
        run: |
          brew install ngrok
          # Force macOS à simuler un écran pour éviter le noir
          sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayResolutionEnabled -bool true
          sudo defaults write /Library/Preferences/com.apple.windowserver.plist DisplayAnywhere -bool true
          echo "✅ Écran virtuel activé"

      - name: Enable VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all -allowAccessFor -allUsers
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes -setvncpw -vncpw P@ssw0rd123!
          echo "✅ VNC prêt avec mot de passe P@ssw0rd123!"

      - name: Start Ngrok Tunnel
        run: |
          # Ton Token est configuré ici
          ngrok authtoken 3EEcwRqdv6kv0zGDXgwiMCzQUdO_6uT6VEasmrbrP2L5UXmC4
          
          echo "🚀 Lancement du tunnel Ngrok..."
          # Lancement du tunnel TCP sur le port VNC 5900
          ngrok tcp 5900 --log=stdout > ngrok.log &
          sleep 10
          
          # Récupération de l'adresse publique
          URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          
          echo "=========================================="
          echo "ADRESSE DE CONNEXION : $URL"
          echo "=========================================="
          
          # Garde le job actif pour 6 heures
          while true; do sleep 60; done
